rm(list = ls())
# import libraries for analysis
library(ggplot2)
library(plotly)
library(scales)
library(tidyverse)
library(mgcv)
require(lmerTest)
require(ncf)
library(ggfortify)
library(glmmTMB)
library(dplyr)
library(AER)

# In this study, I want to explore the gapeworm population dynamics in European starlings.
# Gapeworm ( Syngamus trachea is a parasitic nematode with a complex life cycle that infects the birds' trachea. 
# Starlings get infected from ingesting the encysted parasite larvae in earthworms.
# 370 and 403 starlings (yearlings) were caught and dissected in 2018 and 2019, respectively, from 4 airports.
# I want to figure out the gapeworm numbers change in starlings in the respect of time and also the rainfall level.
# I expect to see a nonlinear relationship here so I will use generalized additive models.
# Also, I will investigate the relationship between bursa/spleen weight and gapeworm infection, without considering time.
##########################################################################################################

# read the csv file for gapeworm data in 2019 and 2018
gapeworm19 <- read_csv("gapeworm19.csv")
gapeworm18 <- read_csv("gapeworm18.csv")

# Have an overview of the data, the column named "N6" is the number of the gapeworms counted in this bird.
# We also have the bird weight, Bursa weight and the Spleen weight recorded. DOC means the date of capture.
# Sum_r means the previous month's (according to the capture date) rainfall for the captured birds.
head(gapeworm19)
head(gapeworm18)

# we can see some NAs in Bursa, spleen weight. I will keep them there, just to allow me have enought 
# gapeworm counts in 2018. When I focus on the bursa and spleen model, I will clean those data.

# Let R read the date, it will show 2021 as the year, but this won't affect the analysis.
gapeworm18$DOC <- as.Date(gapeworm18$DOC,
                          format = "%m/%d")
gapeworm19$DOC <- as.Date(gapeworm19$DOC,
                          format = "%m/%d")

# I will convert the date to how long has it been since the first day. First define the first date.
# I used the first capture date in 2019 because it's the earliest date.
start <- "2021-05-24"
gapeworm19$date_diff <-as.Date(gapeworm19$DOC,
                               format = "%Y-%m-%d") - as.Date(start,format = "%Y-%m-%d")
gapeworm18$date_diff <-as.Date(gapeworm18$DOC,
                               format = "%Y-%m-%d") - as.Date(start,format = "%Y-%m-%d")

# set the date difference as numeric form.
gapeworm18$date_diff <- as.numeric(gapeworm18$date_diff)
gapeworm19$date_diff <- as.numeric(gapeworm19$date_diff)

##############################Part 1######################################
# Let's focusing on the seasonal variation and the rainfall level effects for the gapeworm infection first!
# I will use 2019 data to do the model first, then use the 2018 data for the prediction.
# Look at the data: 
hist(gapeworm19$N6,main = "Historgram of Gapeworm in 2019")
hist(gapeworm18$N6,main = "Historgram of Gapeworm in 2018")
mean(gapeworm19$N6)
mean(gapeworm18$N6)
var(gapeworm19$N6)
var(gapeworm18$N6)
# So many zeros!!
# Also, if we look at the mean and variance for each data, the variance is much larger than the mean is both cases.
# The data are overdispersed.
plot(N6~date_diff,gapeworm19,main = "Gapeworm Counts for Starlings at Different Collecting Date (2019)")
plot(N6~date_diff,gapeworm18,main = "Gapeworm Counts for Starlings at Different Collecting Date (2018)")

# We might need a poisson distribution here for the count data. But the Poisson regression assumes that the
# variance equals to the mean.One way to check this is to look at the residual deviance and the degree of freedom,
# if the ratio between this two larger than 1, that means there's overdispersion.
m_p <- glm(N6~date_diff+Sum_r, data = gapeworm19,family = "poisson")
summary(m_p)

# The residual deviance is 2 times larger than the degrees of freedom. In this case, we might need other way to do the model.
# Or use the overdispersion test, here we do have an overdispered data because of the low p-value.
dispersiontest(m_p)

# Let start fitting our models. I picked two distributions for my data: negative binomial and zero-inflated.
# Negative binomial treats the variance as a quadratic function of the mean.
# Zero-inflated Poisson suggests that the zero counts are generated by another process.
# Why I choose these two?  Empirically, researchers use negative binomial distribution to interpret the
# parasite count data, which most hosts have zero or few parasites and a small portion of hosts have high parasite
# infection. This is the reason why I want to try negative binomial dist here.
# But also, I found Zero-inflated Poisson distribution is also famous, by describing the host might not
# encounter the parasite at all, or their immune system win the fight.
###############################################################################################################

# First solution: use negative binomial distribution.
# I am not sure how to describe the rainfall level in the model, so I tried two ways to put them in.
# 1. Multiply it to the smooth function.
m_nb <- gam(N6~s(date_diff,by = Sum_r), data = gapeworm19,family = "nb")
summary(m_nb)
gam.check(m_nb)
plot(m_nb)
# 2. Simply add it.
m_nb1 <- gam(N6~s(date_diff)+Sum_r, data = gapeworm19,family = "nb")
summary(m_nb1)
gam.check(m_nb1)
plot(m_nb1)

# Second solution: use zero-inflated poisson.
# The same setting as above:
m_zip <- gam(N6~s(date_diff,by = Sum_r), data = gapeworm19,family = ziP())
summary(m_zip)
gam.check(m_zip)
plot(m_zip)

m_zip1 <- gam(N6~s(date_diff)+Sum_r, data = gapeworm19,family = ziP())
summary(m_zip1)
gam.check(m_zip1)
plot(m_zip1)

# Compare: I don't see a huge difference in AIC values for how to describe rainfall.
# But, it seems that nb models are generally better than ZIP model with a low AIC value.
AIC(m_nb,m_nb1,m_zip,m_zip1)

# Let's compare the predicted value to the observed value to see which model can get a better fit.
# In this case, I need to calculate the mean gapeworm load for each date, to see how the model fit.
D19 <- data.frame(gapeworm19$N6,gapeworm19$Sum_r,gapeworm19$date_diff)
D19 <- D19 %>% group_by(gapeworm19.date_diff) %>% summarise(across(everything(), list(mean)))
D19 <- D19%>% 
  rename(date = gapeworm19.date_diff)
D19 <- D19%>% 
  rename(Mean_N6 = gapeworm19.N6_1)
D19 <- D19%>% 
  rename(Rain = gapeworm19.Sum_r_1)
D19$date <- as.numeric(D19$date)

D18 <- data.frame(gapeworm18$N6,gapeworm18$date_diff,gapeworm18$Sum_r)
D18 <- D18 %>% group_by(gapeworm18.date_diff) %>% summarise(across(everything(), list(mean)))
D18 <- D18%>% 
  rename(date = gapeworm18.date_diff)
D18 <- D18%>% 
  rename(Mean_N6 = gapeworm18.N6_1)
D18 <- D18%>% 
  rename(Rain = gapeworm18.Sum_r_1)
D18$date <- as.numeric(D18$date)

# Model prediction: Blue means 2018, Red means 2019
# Predict the model: Negative binomial group
# Add
Pr1 <- data.frame(date_diff = gapeworm18$date_diff,Sum_r = gapeworm18$Sum_r)
Pr2 <- data.frame(date_diff = gapeworm19$date_diff,Sum_r = gapeworm19$Sum_r)
Pr1$mod <- predict(m_nb1, newdata=Pr1, type='response')
Pr1$modse <- predict(m_nb1, newdata=Pr1, type='response', se.fit=TRUE)$se.fit
Pr2$mod2 <- predict(m_nb1, newdata=Pr2, type ='response')
Pr2$mod2se <- predict(m_nb1, newdata=Pr2, type='response', se.fit=TRUE)$se.fit

ggplot() +
  geom_point(data = D18, aes(x=date, y = Mean_N6,color = "2018"))+
  geom_point(data = D19, aes(x=date, y = Mean_N6,color = "2019"))+
  geom_line(data=Pr1, aes(x=as.numeric(date_diff), y=mod,color = "2018"))+
  geom_line(data=Pr2, aes(x=as.numeric(date_diff), y=mod2,color = "2019"))+
  geom_ribbon(data=Pr2, aes(x=date_diff, ymin=mod2-mod2se, ymax=mod2+mod2se, fill='2019'), alpha=0.3, inherit.aes=FALSE)+
  geom_ribbon(data=Pr1, aes(x=date_diff, ymin=mod-modse, ymax=mod+modse,fill='2018'), alpha=0.3,  inherit.aes=FALSE)+
  theme_bw()+
  ggtitle("Gapeworm Abundance Prediction: Add Rainfall Term")+
  labs(y = "Gapeworm Infection")

# Multiply
Pr3 <- data.frame(date_diff = gapeworm18$date_diff,Sum_r = gapeworm18$Sum_r)
Pr4 <- data.frame(date_diff = gapeworm19$date_diff,Sum_r = gapeworm19$Sum_r)
Pr3$mod <- predict(m_nb, newdata=Pr3, type='response')
Pr3$modse <- predict(m_nb, newdata=Pr3, type='response', se.fit=TRUE)$se.fit
Pr4$mod2 <- predict(m_nb, newdata=Pr4, type ='response')
Pr4$mod2se <- predict(m_nb, newdata=Pr4, type='response', se.fit=TRUE)$se.fit

ggplot() +
  geom_point(data = D18, aes(x=date, y = Mean_N6,color = "2018"))+
  geom_point(data = D19, aes(x=date, y = Mean_N6,color = "2019"))+
  geom_line(data=Pr3, aes(x=as.numeric(date_diff), y=mod,color = "2018"))+
  geom_line(data=Pr4, aes(x=as.numeric(date_diff), y=mod2,color = "2019"))+
  geom_ribbon(data=Pr4, aes(x=date_diff, ymin=mod2-mod2se, ymax=mod2+mod2se, fill='2019'), alpha=0.3, inherit.aes=FALSE)+
  geom_ribbon(data=Pr3, aes(x=date_diff, ymin=mod-modse, ymax=mod+modse,fill='2018'), alpha=0.3,  inherit.aes=FALSE)+
  theme_bw()+
  ggtitle("Gapeworm Abundance Prediction: Multiply Rainfall Term")+
  labs(y = "Gapeworm Infection")

# It seems that if we multiply the rainfall, the prediction can be closer to the observed value. 
# How about ZIP model? Do a prediction for the multiply rainfall one.
Pr5 <- data.frame(date_diff = gapeworm18$date_diff,Sum_r = gapeworm18$Sum_r)
Pr6 <- data.frame(date_diff = gapeworm19$date_diff,Sum_r = gapeworm19$Sum_r)
Pr5$mod <- predict(m_zip, newdata=Pr5, type='response')
Pr5$modse <- predict(m_zip, newdata=Pr5, type='response', se.fit=TRUE)$se.fit
Pr6$mod2 <- predict(m_zip, newdata=Pr6, type ='response')
Pr6$mod2se <- predict(m_zip, newdata=Pr6, type='response', se.fit=TRUE)$se.fit

ggplot() +
  geom_point(data = D18, aes(x=date, y = Mean_N6),color = "blue")+
  geom_point(data = D19, aes(x=date, y = Mean_N6),color = "red")+
  geom_line(data=Pr5, aes(x=as.numeric(date_diff), y=mod),color = "blue")+
  geom_line(data=Pr6, aes(x=as.numeric(date_diff), y=mod2),color = "red")+
  geom_ribbon(data=Pr6, aes(x=date_diff, ymin=mod2-mod2se, ymax=mod2+mod2se), alpha=0.3, fill='red', inherit.aes=FALSE)+
  geom_ribbon(data=Pr5, aes(x=date_diff, ymin=mod-modse, ymax=mod+modse), alpha=0.3, fill='blue', inherit.aes=FALSE)

# I think the negative binomial model might be the best one in this case.
############################################################################################
############################################################################################
# Part two: Bursa and Spleen weight vs. gapeworm infection, without the effects of time.
# I expect a linear relationship between bursa/spleen weight and the gapeworm infection.
# Bursa and spleen are two organs that influence the birds' immune response.

# Clean the data, filter the NA values
gapeworm19 <- filter(gapeworm19, Weight != "NA")
gapeworm19 <- filter(gapeworm19, Spleen != "NA")
gapeworm19 <- filter(gapeworm19, Bursa != "NA")
gapeworm18 <- filter(gapeworm18, Weight != "NA")
gapeworm18 <- filter(gapeworm18, Spleen != "NA")
gapeworm18 <- filter(gapeworm18, Bursa != "NA")
# I will add two years data up to build the model
all <- rbind(gapeworm18,gapeworm19)
# Look at the distribution first
# Wait! Will a big bird have a bigger bursa/spleen? I need to check it.
# It seems that Bursa and Spleen all positively related to the bird weight.

plot(N6~Bursa,data = all)
plot(N6~Spleen,data = all)
plot(N6~Weight,data = all)
plot(Bursa~Weight,data = all)
plot(Spleen~Weight,data = all)

# Run two linear models for bursa/spleen vs. weight
# It seems that weight might have small effect on bursa and spleen size.

bw <- lm(Bursa~Weight,data = all)
summary(bw)

sw <- lm(Spleen~Weight,data = all)
summary(sw)

# To simply avoid the effects from weight, I will use bursa(spleen)/weight to run the model.
# Fit a generalized linear mixed-effects model (GLMM) with negative binomial distribution
# I will use date_diff and Sum_r as random effect
# Bursa weight vs. gapeworm counts
b1 <- glmer.nb(N6~Bursa/Weight +(1|date_diff)+(1|Sum_r), data = all)
summary(b1)


Bu <- data.frame(Bursa = sample(seq(from = 0, to = 1,by = 0.01),size=565,replace=TRUE),
                 date_diff = all$date_diff,Sum_r = all$Sum_r,Weight = all$Weight)
Bu$mod <- predict(b1, newdata=Bu, type='response')
ggplot() +
  geom_point(data = Bu, aes(x=Bursa, y = mod),color = "blue")+
  geom_smooth(data = Bu,aes(x=Bursa, y = mod),se = FALSE,color = "red")+
  theme_bw()+
  labs(y = "Predicted Gapeworm Infection")
# We can see a clear negative relationship between Bursa weight and gapeworm infection.

# Spleen weight vs. gapeworm counts
# No clear relationship detected.
b2 <- glmer.nb(N6~Spleen/Weight+(1|date_diff)+(1|Sum_r), data = all)
summary(b2)
plot(b2$residuals~all$Weight)
Sl <- data.frame(Spleen = sample(seq(from = 0, to = 1,by = 0.01),size=565,replace=TRUE),
                 date_diff = all$date_diff,Sum_r = all$Sum_r,Weight = all$Weight)
Sl$mod <- predict(b2, newdata=Sl, type='response')
ggplot() +
  geom_point(data = Sl, aes(x=Spleen, y = mod),color = "blue")+
  geom_smooth(data = Sl,aes(x=Spleen, y = mod),se = FALSE,color = "red")+
  theme_bw()+
  labs(y = "Predicted Gapeworm Infection")